---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: jenkins-http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "jenkins.rizkidoank.internal"
  - port:
      number: 443
      name: jenkins-https 
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-selfsigned-cert
    hosts:
    - "argocd.rizkidoank.internal"      
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs
spec:
  hosts:
  - "jenkins.rizkidoank.internal"
  gateways:
  - jenkins-gw
  http:
  - route:
    - destination:
        host: jenkins-app.develop.svc.cluster.local
        port:
          number: 80
---