apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-selfsigned-cert
  namespace: istio-system
spec:
  secretName: wildcard-selfsigned-cert
  commonName: '*.rizkidoank.internal'
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
  - rizkidoank.internal
  - '*.rizkidoank.internal'
