---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway-develop
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "argocd.rizkidoank.internal"      
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-server
spec:
  hosts:
  - "argocd.rizkidoank.internal"
  gateways:
    - ingressgateway-develop
  http:
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http-grafana
      number: 80
      protocol: HTTP
    hosts:
    - "grafana.rizkidoank.internal"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
spec:
  hosts:
  - "grafana.rizkidoank.internal"
  gateways:
  - grafana-gw
  http:
  - route:
    - destination:
        host: prometheus-operator-app-grafana.develop.svc.cluster.local
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana-dr
spec:
  host: prometheus-operator-app-grafana.develop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
