---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: argo-http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "argocd.rizkidoank.internal"
  - port:
      number: 443
      name: argo-https 
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-selfsigned-cert
    hosts:
    - "argocd.rizkidoank.internal"      
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-vs
spec:
  hosts:
  - "argocd.rizkidoank.internal"
  gateways:
  - argocd-gw
  http:
  - route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: grafana-http
      number: 80
      protocol: HTTP
    hosts:
    - "grafana.rizkidoank.internal"
  - port:
      name: grafana-https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-selfsigned-cert
    hosts:
    - "grafana.rizkidoank.internal"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
spec:
  hosts:
  - "grafana.rizkidoank.internal"
  gateways:
  - grafana-gw
  http:
  - route:
    - destination:
        host: prometheus-operator-app-grafana.develop.svc.cluster.local
        port:
          number: 80
