apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: release/argocd-app/charts/prometheus-operator
    repoURL: https://github.com/rizkidoank/kubernetes-ops.git
    targetRevision: develop
  ignoreDifferences:
  - group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name: mutatingwebhookignore
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: validatingwebhookignore
    jsonPointers:
    - /webhooks
