apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    helm:
      parameters:
      - name:  service.type
        value: LoadBalancer
      - name: service.spec.loadBalancerIP
        value: "192.168.2.151"
      valueFiles:
      - values.yaml
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 9.3.0
