apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      parameters:
      - name: alertmanager.enabled
        value: "false"
      - name: grafana.ingress.enabled
        value: "true"
      - name: grafana.ingress.hosts[0]
        value: "grafana.rizkidoank.internal"
      - name: grafana.ingress.annotations."kubernetes\.io/ingress\.class"
        value: "traefik"
      valueFiles:
      - values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.4.4
