apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        alertmanager:
          enabled: false

        grafana:
          enabled: true
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/ssl-passthrough: true
            hosts:
              - grafana.rizkidoank.internal
            path: /
            tls:
              - secretName: wildcard-cert
                hosts:
                  - grafana.rizkidoank.internal
      
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.4.4
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: crdignore
      jsonPointers:
      - /status
    - group: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: mutatingwebhookignore
      jsonPointers:
      - /webhooks
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: validatingwebhookignore
      jsonPointers:
      - /webhooks
