apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openfaas
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: openfaas
    helm:
      values: |
      
      prometheus:
        create: false
      alertmanager:
        create: false
      ingress:
        enabled: true
        hosts:
          - host: openfaas.rizkidoank.internal
            serviceName: gateway
            servicePort: 8080
            path: /
        annotations:
          kubernetes.io/ingress.class: traefik

    repoURL: https://openfaas.github.io/faas-netes/
    targetRevision: 6.0.4
  syncPolicy:
    automated:
      prune: true
